/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f103x6.h"
#include "GPIO.h"
#include "EXTI.h"
#include "Lcd.h"
#include "KeyPad.h"
#include "Seven_Segment.h"
#include "RCC.h"
#include "USART.h"

    uint16_t Data;

void UART_IRQ_Callback (void)
{

	MCAL_USART_ReceiveData(USART1, &Data, PollingMechanism_Dis);
	MCAL_USART_SendData(USART1, &Data, 	PollingMechanism_EN);

}
int main(void)
{

    RCC_AFIO_CLK_EN();
    RCC_GPIOA_CLK_EN();


    USART_Config_t uartConfig;
    uartConfig.BaudRate      = USART_BaudRate_115200;
    uartConfig.DataSize      = USART_DataSize_8bit;
    uartConfig.FlowCtrl      = USART_CTS_RTS_Disable;
    uartConfig.IRQ_Enable    = USART_IRQ_Enable_RXNEIE  ;
    uartConfig.Parity        = USART_Parity_Disable;
    uartConfig.Ptr_ISR_Func  = UART_IRQ_Callback;
    uartConfig.StopBitNo     = USART_StopBitNo_1;
    uartConfig.USART_Mode    = USART_Mode_TX_RX_Enable;

    MCAL_USART_GPIO_Set_Pins(USART1);

    MCAL_USART_Init(USART1, &uartConfig);




    while(1)
    {

    	// by using Polling Mechanism
    	// MCAL_USART_ReceiveData(USART1, &Data, PollingMechanism_EN);
    	// MCAL_USART_SendData(USART1, &Data, PollingMechanism_EN);
    	// MCAL_USART_WAIT_TC(USART1);


    }
}




